[2024-03-10 17:28:22,564] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.75.163:5000
[2024-03-10 17:28:22,564] INFO in _internal: [33mPress CTRL+C to quit[0m
[2024-03-10 17:28:51,113] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:28:51] "[33mGET / HTTP/1.1[0m" 404 -
[2024-03-10 17:28:51,219] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:28:51] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2024-03-10 17:44:49,838] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 60, in get
    reviews = PokeReview.query.filter_by(pokemon_name=name).all()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:44:50,083] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:44:50] "[35m[1mGET /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:44:51,011] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 60, in get
    reviews = PokeReview.query.filter_by(pokemon_name=name).all()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:44:51,091] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:44:51] "[35m[1mGET /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:45:09,870] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:45:09] "[31m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 400 -
[2024-03-10 17:46:04,924] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 38, in post
    db.session.commit()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj
    for (
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 994, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1130, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:46:04,957] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:46:04] "[35m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:46:48,501] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 38, in post
    db.session.commit()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj
    for (
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 994, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1130, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:46:48,534] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:46:48] "[35m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:47:24,777] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 38, in post
    db.session.commit()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj
    for (
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 994, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1130, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:47:24,839] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:47:24] "[35m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:47:35,266] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 38, in post
    db.session.commit()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj
    for (
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 994, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1130, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:47:35,303] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:47:35] "[35m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:51:26,493] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 38, in post
    db.session.commit()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj
    for (
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 994, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1130, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:51:26,517] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:51:26] "[35m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:52:55,344] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 60, in get
    reviews = PokeReview.query.filter_by(pokemon_name=name).all()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:52:55,397] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:52:55] "[35m[1mGET /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:53:04,912] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:53:04] "GET /pokemon/poke/charizard HTTP/1.1" 200 -
[2024-03-10 17:53:36,073] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 38, in post
    db.session.commit()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj
    for (
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 994, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1130, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:53:36,113] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:53:36] "[35m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:55:26,164] ERROR in review: Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniproject\python\mvenv\flask-template-venv\app\apis\pokemon\resources\poke\review.py", line 38, in post
    db.session.commit()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj
    for (
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 994, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1130, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\miniproject\python\mvenv\flask-template-venv\myenv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

[2024-03-10 17:55:26,202] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:55:26] "[35m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 500 -
[2024-03-10 17:56:39,329] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.75.163:5000
[2024-03-10 17:56:39,329] INFO in _internal: [33mPress CTRL+C to quit[0m
[2024-03-10 17:56:39,339] INFO in _internal:  * Restarting with stat
[2024-03-10 17:56:49,857] WARNING in _internal:  * Debugger is active!
[2024-03-10 17:56:49,910] INFO in _internal:  * Debugger PIN: 385-825-788
[2024-03-10 17:57:03,097] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:57:03] "POST /pokemon/poke/charizard/review HTTP/1.1" 200 -
[2024-03-10 17:59:03,333] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:59:03] "GET /pokemon/poke/pikachu HTTP/1.1" 200 -
[2024-03-10 17:59:27,955] INFO in _internal: 192.168.75.163 - - [10/Mar/2024 17:59:27] "GET /pokemon/poke/charizard/review HTTP/1.1" 200 -
[2024-03-12 07:18:46,570] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.247.163:5000
[2024-03-12 07:18:46,570] INFO in _internal: [33mPress CTRL+C to quit[0m
[2024-03-12 07:18:46,570] INFO in _internal:  * Restarting with stat
[2024-03-12 07:18:55,895] WARNING in _internal:  * Debugger is active!
[2024-03-12 07:18:55,909] INFO in _internal:  * Debugger PIN: 944-064-375
[2024-03-12 08:09:41,548] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.247.163:5000
[2024-03-12 08:09:41,549] INFO in _internal: [33mPress CTRL+C to quit[0m
[2024-03-12 08:09:41,552] INFO in _internal:  * Restarting with stat
[2024-03-12 08:10:14,101] WARNING in _internal:  * Debugger is active!
[2024-03-12 08:10:14,111] INFO in _internal:  * Debugger PIN: 944-064-375
[2024-03-12 10:40:43,537] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.247.163:5000
[2024-03-12 10:40:43,538] INFO in _internal: [33mPress CTRL+C to quit[0m
[2024-03-12 10:40:43,543] INFO in _internal:  * Restarting with stat
[2024-03-12 10:41:15,992] WARNING in _internal:  * Debugger is active!
[2024-03-12 10:41:16,048] INFO in _internal:  * Debugger PIN: 944-064-375
[2024-03-12 21:39:04,912] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.247.163:5000
[2024-03-12 21:39:04,912] INFO in _internal: [33mPress CTRL+C to quit[0m
[2024-03-12 21:39:04,927] INFO in _internal:  * Restarting with stat
[2024-03-12 21:39:15,025] WARNING in _internal:  * Debugger is active!
[2024-03-12 21:39:15,082] INFO in _internal:  * Debugger PIN: 852-210-946
[2024-03-12 21:53:13,901] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.247.163:5000
[2024-03-12 21:53:13,901] INFO in _internal: [33mPress CTRL+C to quit[0m
[2024-03-12 21:53:13,910] INFO in _internal:  * Restarting with stat
[2024-03-12 21:53:24,167] WARNING in _internal:  * Debugger is active!
[2024-03-12 21:53:24,194] INFO in _internal:  * Debugger PIN: 852-210-946
[2024-03-12 22:20:38,633] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.247.163:5000
[2024-03-12 22:20:38,639] INFO in _internal: [33mPress CTRL+C to quit[0m
[2024-03-12 22:20:38,641] INFO in _internal:  * Restarting with stat
[2024-03-12 22:20:49,083] WARNING in _internal:  * Debugger is active!
[2024-03-12 22:20:49,105] INFO in _internal:  * Debugger PIN: 852-210-946
[2024-03-12 22:55:32,963] INFO in _internal: 127.0.0.1 - - [12/Mar/2024 22:55:32] "[31m[1mPOST /pokemon/poke/charizard/review HTTP/1.1[0m" 400 -
